# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BlackDoc- Title edited
tagline:          Black Theme for Jekyll
description:      "Testing something something"
url:              https://FreesteamWGUI.github.io
baseurl:          /

author:
  name:           'Shemsi Shneta'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/FreesteamWGUI/FreesteamWGUI.github.io
